### ISSUE TITLE
Strange error - can't run magic

### ISSUE THREAD

**Issue by piotrkochan** [eko/docker-symfony#10]
docker-compose up

Warning: the mapping "symfony:/var/www/symfony" in the volumes config for service "application" is ambiguous. In a future version of Docker, it will designate a "named" volume (see https://github.com/docker/docker/pull/14242). To prevent unexpected behaviour, change it to "./symfony:/var/www/symfony"
Warning: the mapping "logs/symfony:/var/www/symfony/app/logs" in the volumes config for service "application" is ambiguous. In a future version of Docker, it will designate a "named" volume (see https://github.com/docker/docker/pull/14242). To prevent unexpected behaviour, change it to "./logs/symfony:/var/www/symfony/app/logs"
Warning: the mapping "logs/nginx/:/var/log/nginx" in the volumes config for service "nginx" is ambiguous. In a future version of Docker, it will designate a "named" volume (see https://github.com/docker/docker/pull/14242). To prevent unexpected behaviour, change it to "./logs/nginx/:/var/log/nginx"
Warning: the mapping "elk/logstash:/etc/logstash" in the volumes config for service "elk" is ambiguous. In a future version of Docker, it will designate a "named" volume (see https://github.com/docker/docker/pull/14242). To prevent unexpected behaviour, change it to "./elk/logstash:/etc/logstash"
Warning: the mapping "elk/logstash/patterns:/opt/logstash/patterns" in the volumes config for service "elk" is ambiguous. In a future version of Docker, it will designate a "named" volume (see https://github.com/docker/docker/pull/14242). To prevent unexpected behaviour, change it to "./elk/logstash/patterns:/opt/logstash/patterns"
client and server don't have same version (client : 1.19, server: 1.12)

docker -v

> Docker version 1.0.1, build 990021a

docker-compose -v

> docker-compose version: 1.4.0

**Comment by eko** [comment]
Hello,

Closing this issue as this problem is now fixed.

Thank you
