### ISSUE TITLE
Real Ip from the request

### ISSUE THREAD

**Issue by oscarpedrero** [eko/docker-symfony#103]
I cant get the real ip of request on Symfony, can you help me to config nginx?

**Comment by eko** [comment]
Hi @oscarpedrero,

This is not a docker-symfony issue but I understand that you open the issue here.

You can have a look on Symfony's trusted proxies to be able to retrieve the real IP forwarded by nginx: https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies

Thank you
