### ISSUE TITLE
Next, put your Symfony application into symfony

### ISSUE THREAD

**Issue by grekpg** [eko/docker-symfony#104]
If i create new application i should use  

composer create-project symfony/website-skeleton symfony in root dir ? 
Can You show example how to run new symfony aplication in this docker-compose ?

I create new Symfony project - 
`composer create-project symfony/website-skeleton symfony`
then 
` docker-compose up`
 now i see in http://symfony.localhost/ 
```

(1/1) RuntimeException
Unable to write in the logs directory (/var/www/symfony/var/log)
```
i try change permisions : 

`sudo chmod 777 symfony/var/log -R`

but error still exist

**Comment by grekpg** [comment]
ok  sudo chmod 0777 symfony/var/log -R

**Comment by Shyroby** [comment]
Probably obviously but to be more specific, chmod 0777 want to be execute on php running container, in which root permissions are by default available. 
Step by step we have to do: 

- docker exec -it <containerID> sh
- chmod 0777 symfony/var/log -R
