### ISSUE TITLE
Connexion Symfony 4 avec la base de données

### ISSUE THREAD

**Issue by YLassina** [eko/docker-symfony#105]
Bonjour,
je n'arrive pas creer la base de données avec symfony 4 j'essaye depuis plusieurs jours sans succès 
![capture d ecran 2019-01-06 a 11 40 11](https://user-images.githubusercontent.com/43670315/50735565-09055380-11a9-11e9-9ff0-7ba830b931ff.png)
![capture d ecran 2019-01-06 a 11 41 11](https://user-images.githubusercontent.com/43670315/50735566-099dea00-11a9-11e9-8a59-0d6f293d1958.png)

**Comment by jaudette** [comment]
Même problème ici.
J'ai aussi essayé avec symfony/symfony

Docker sur windows.
