### ISSUE TITLE
How to enable CORS ?

### ISSUE THREAD

**Issue by SergioMartinSanchez** [eko/docker-symfony#107]
Someone knows how to enable the cors in the nginx, I have already enabled the cors inside the symfony but now I can not get the nginx to have it enabled.
This is a snapshot of my client (ionic4 pwa) trying to connect to the server.
![image](https://user-images.githubusercontent.com/10806524/53601658-dece8180-3bac-11e9-9e7d-b0e898e9feb8.png)

If you could help me, I'd appreciate it enormously!!!
Thx!

**Comment by ctukc-nt** [comment]
Hi, what bandl do you use?
I'm use nelmio/cors-bundle and my conf config/packages/nelmio_cors.yaml
`nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
    paths:
       '^/api/':
           allow_origin: ['*']
           allow_headers: ['*']
           allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
           max_age: 0
       '^/files/':
           allow_origin: ['*']
           allow_headers: ['*']
           allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
           max_age: 0
`

Hope, this help.

**Comment by SergioMartinSanchez** [comment]
> Hi, what bundle do you use?
> I'm use nelmio/cors-bundle and my conf config/packages/nelmio_cors.yaml
> `nelmio_cors: defaults: allow_credentials: false allow_origin: [] allow_headers: [] allow_methods: [] expose_headers: [] max_age: 0 paths: '^/api/': allow_origin: ['*'] allow_headers: ['*'] allow_methods: ['POST', 'PUT', 'GET', 'DELETE'] max_age: 0 '^/files/': allow_origin: ['*'] allow_headers: ['*'] allow_methods: ['POST', 'PUT', 'GET', 'DELETE'] max_age: 0`
> 
> Hope, this help.

Thank you for the quick reply.
I have cors at symfony level well configured.
I tell my problem, I if I do out of docker the php bin/console server:run I have no cors problems, but if I try to access the symfony by the nginx container I get cors error.

**Comment by SergioMartinSanchez** [comment]
Hey, thanks a lot!!!
with this configuration is fixed, close the issue
