### ISSUE TITLE
.localhost doesn't work in Google Chrome

### ISSUE THREAD

**Issue by iproger** [eko/docker-symfony#109]
> There's also an excellent proposal to add the .localhost domain as a new standard, which would be more appropriate here. It would mean we no longer have site.dev, but site.localhost. And everything at *.localhost would automatically translate to 127.0.0.1, without /etc/hosts or dnsmasq workarounds.
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by wabbenhuis** [comment]
To support any domain-name you could remove the `server_name symfony.localhost;` in `./nginx/symfony.conf`.

Or add the new virtualhost as a server-block or alias.

**Comment by eko** [comment]
Hi,

@wabbenhuis is right.

Thank you, closing this issue now. Feel free to reopen if you have any question.
