### ISSUE TITLE
Creating files from php container

### ISSUE THREAD

**Issue by Gabb1995** [eko/docker-symfony#118]
So I'm creating files using symfony commands inside the php fpm container for example from the makerbundle. But then these files on my host machine are root:root, is it possible for them to have the same permission as my current user?

**Comment by wabbenhuis** [comment]
Your docker Deamon is run as root on the host.
Therefor it will generate root:root chown'ed files. 

You can change this in multiple ways but, combined with docker-compose, none of them are ideal or easier them chown'ing them after running maker commands.

**Comment by eko** [comment]
Thanks for helping each other in this subject!

Closing this now
