### ISSUE TITLE
Why debian:jessie ?

### ISSUE THREAD

**Issue by ludofleury** [eko/docker-symfony#12]
Hello, simple question here, why debian:jessie for the code instead of a busybox ? just to save space & reuse the layer ?

**Comment by robertwe** [comment]
I would say because it's way much easier to put something into Debian/CentOS image than in the BusyBox. From what I know on the hub there is a huge amount of images based on Ubuntu (got the biggest base image). Personally I use CentOs7 image as my base image.

**Comment by eko** [comment]
Hello,

Project is now using alpine distribution images. Closing this issue now.

Thank you
