### ISSUE TITLE
Problem exec it bash in service

### ISSUE THREAD

**Issue by shubaivan** [eko/docker-symfony#121]
when I try to enter in someone service 

```
docker exec -it nginx bash
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
```
but example `docker-compose exec php php /var/www/symfony/bin/console cache:clear`  works
this is correct behaviour ? or how to enter in service?

**Comment by maxtorete** [comment]
With Alpine images you should use ash instead of bash:

docker exec -it nginx ash

**Comment by shubaivan** [comment]
thank you, everything works correct
