### ISSUE TITLE
php 7.4

### ISSUE THREAD

**Issue by mathieudureisseix** [eko/docker-symfony#122]
Hi,
thanks for the repo. It is very helpfull
Do you know when php 7.4 will be released ?
Thanks
Mathieu

**Comment by eko** [comment]
Hi @mathieudureisseix,

Thank you for your feedback.
The PHP version depends on Alpine packages and actually even on the edge version they only serve PHP 7.3.14r0 version, see: https://pkgs.alpinelinux.org/packages?name=php7&branch=edge

I hope they will update the version on Alpine 3.12.

Closing this issue as there is no real issue here.

**Comment by jorrit** [comment]
Isn't it an option to use the php Docker image? It also has an alpine variant and it offers PHP 7.4.

**Comment by MylesKingsnorth** [comment]
Any update on this?

**Comment by BurningDog** [comment]
Alpine edge now supports php 7.4 - to use it, edit https://github.com/eko/docker-symfony/blob/master/php-fpm/Dockerfile and change the first line to `FROM alpine:edge` then run `docker-compose build` to rebuild the containers and `docker-composer up` to start everything up:

Before:

```
docker exec -it php-fpm php -v
PHP 7.3.25 (cli) (built: Nov 26 2020 13:43:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.25, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.25, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
```

After:

```
docker exec -it php-fpm php -v
PHP 7.4.13 (cli) (built: Dec  7 2020 20:58:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans
```
