### ISSUE TITLE
How can I save all my data from one strating to another?

### ISSUE THREAD

**Issue by Pum-purum** [eko/docker-symfony#123]
Database is clear every time I launched docker :(

**Comment by Coderberg** [comment]
Андрей, try to add something like this:
```
volumes:
       - /mysql:/var/lib/mysql
```

**Comment by Pum-purum** [comment]
But what if i use Docker on Windows machine ?

**Comment by eko** [comment]
@Pum-purum  @Coderberg is right, you can mount your data into a directory. It works both on Linux, MacOS and Windows, so you can specify a Windows directory, such as:

```
volumes:
       - C:\data\mysql:/var/lib/mysql
```

Please close this issue once it's OK for you.

Thank you
