### ISSUE TITLE
How to config xdebug in PHPstorm

### ISSUE THREAD

**Issue by CarlosGude** [eko/docker-symfony#124]
Hi, I tried config Xdebug in PHPstorm but not works.

I added _"php7-xdebug \"_ to dockerfile.
The CLI interpreter is "docker-symfony_php:latest (7.3.14)"
The path mappings is /var/www/symfony

Can someone help me?

regards

**Comment by MrKarolisS** [comment]
I have same issues. Can't connect to xdebug.

Xdebug logs out: 
```
[6] Log opened at 2020-02-23 17:18:55
[6] I: Connecting to configured address/port: host.docker.internal:5902.
[6] E: Time-out connecting to client (Waited: 200 ms). :-(
[6] Log closed at 2020-02-23 17:18:55
```

PHPStorm debug port is set on 5902. As well in docker compose I exposed 5902 port, but still no success.

**Comment by jareis** [comment]
Hi,

xdebug may not have been started.

try to add `xdebug.remote_autostart=true` to xdebug.ini and restart.

more info in https://xdebug.org/docs/remote#remote_autostart

**Comment by CarlosGude** [comment]
I still have the same problem. 

Can you put some captures of your phpstorm configuration?

It is to know what configuration you have and put it the same.

**Comment by shubaivan** [comment]
try this, in `php-fpm/xdebug.ini`

```
[Xdebug]
xdebug.remote_enable=true
xdebug.remote_port=5902
xdebug.remote_host=172.17.0.1 //should be ip

xdebug.remote_handler=dbgp
xdebug.remote_autostart=1
xdebug.remote_connect_back=0
xdebug.idekey=docker
xdebug.show_error_trace = 1
xdebug.max_nesting_level=250
xdebug.var_display_max_depth=10
xdebug.remote_mode=req
```

and in Setting -> Language and Framework -> PHP -> Debug

set `Debug port` equal 5902. and check `Break at first line` Then `docker system prune -a` and `docker-compose up`. Then open `http://symfony.localhost/` shuold works
then just enable icon phone in storm and try

**Comment by kasteckis** [comment]
You can try to append your `Dockerfile` by adding the following:
```RUN pecl install xdebug-2.9.6 && docker-php-ext-enable xdebug
RUN echo 'zend_extension="/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so"' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/php.ini```

[You can check this for reference](https://github.com/kasteckis/symfony-docker-compose/blob/master/.docker/Dockerfile)

**Comment by eko** [comment]
You can learn more in the following section on how to enable XDebug: https://github.com/eko/docker-symfony#use-xdebug

Also, a configuration file is available here with some default values: https://github.com/eko/docker-symfony/blob/master/php-fpm/xdebug.ini

Closing this issue for now, feel free to reopen if you still have any issue.

Thank you
