### ISSUE TITLE
How to set logs in ElasticSearch and look it in Kibana ? 

### ISSUE THREAD

**Issue by shubaivan** [eko/docker-symfony#125]
I added service 

```
Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler: ~
```

and handler

```
        es:
            type: service
            id: Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler
```

and faced wth error

```
Next Symfony\Component\HttpClient\Exception\TransportException: Couldn't connect to server for "http://127.0.0.1:9200/_bulk". in /var/www/symfony/vendor/symfony/http-client/Chunk/ErrorChunk.php:52
Stack trace:
#0 /var/www/symfony/vendor/symfony/monolog-bridge/Handler/ElasticsearchLogstashHandler.php(138): Symfony\Component\HttpClient\Chunk\ErrorChunk->isTimeout()

```

how to configuration correct host and port for elasticsearch ?

**Comment by eko** [comment]
Hi @shubaivan,

Code is running inside the container so for the PHP container, 127.0.0.1:9200 does not exists, you should update your configuration to specify `elasticsearch:9200` (see container name: https://github.com/eko/docker-symfony/blob/master/docker-compose.yml#L42).

I hope it helps, closing this issue for now as it's not directly related to this repository code.

Do not hesitate to reply if you have any question.

Thank you
