### ISSUE TITLE
migration xdebug from 2 to 3

### ISSUE THREAD

**Issue by maranqz** [eko/docker-symfony#132]
Right now, xdebug in php 8 is not work correct because of using xdebug v3 with configuration for v2. 
https://xdebug.org/docs/upgrade_guide

**Comment by automatix** [comment]
This issue is going to be resolved by this [PR](https://github.com/eko/docker-symfony/pull/134).

**Comment by eko** [comment]
Thank you for this fix, the PR is now merged si I close this issue.
