### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by automatix** [eko/docker-symfony#138]
Hi @eko,

I've just created a PR. It's very harmless and only extends the `.gitignore` with the PhpStorm config files. But the Travis build failed. Seems to be an account plan related issue:

> ERROR: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by eko** [comment]
Thank you, this PR is now merged so I close this issue.
