### ISSUE TITLE
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'

### ISSUE THREAD

**Issue by francescomalatesta** [eko/docker-symfony#14]
I am getting this error while starting everything with docker-compose up.

I already tried building everything first and then docker-compose up, but no improvements.

Any ideas?

**Comment by francescomalatesta** [comment]
Resolved. It seems that the mysql part docker-compose.yml has two "root" users. Fixed it by changing the username and password with something different from "root".

**Comment by lrkwz** [comment]
Better change docker-compose in the repository; or not?

**Comment by GabLeRoux** [comment]
I had the same, I suggest we change it in the repo too ;)
