### ISSUE TITLE
don't have access to Kibana

### ISSUE THREAD

**Issue by SulivanDotEu** [eko/docker-symfony#15]
Hi there! First of all, thanks for this contribution, so usefull !!

I'm trying to access to kibana through this url : http://symfony.dev:81/ but it's doesn't work.
Message : ERR_CONNECTION_REFUSED

Here is my Vagrantfile, I change the IP of my host docker machine.

   VAGRANTFILE_API_VERSION = "2"

```
  Vagrant.configure(2) do |config|

    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "192.168.20.100"
    config.vm.hostname = "zzz-1"

    config.vm.provision :docker
    config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", rebuild: true, run: "always"

  end
```

**Comment by ypereirareis** [comment]
Hi !

It seeme that your port is not forwarded between your VM and your host.

See : https://docs.vagrantup.com/v2/networking/forwarded_ports.html

Bye

**Comment by eko** [comment]
Hello,

Indeed, it seems your port is not forwarded: closing this issue has it is more a Vagrant issue than a docker-symfony one.

Thank you
