### ISSUE TITLE
Windows folder share

### ISSUE THREAD

**Issue by ndoulgeridis** [eko/docker-symfony#24]
Hello,

I use boot2docker in windows 10 machine. I have successfully mounted my windows folder from Windows to boot2docker but now how to tell docker-compose.yml to mount the folder from boot2docker to the application code container? (i want to mount the folder to /var/www/symfony folder you use so I can develop from windows and see changes live)

**Comment by eko** [comment]
Hello,

You don't have to tell docker-compose to mount the folder has it is already written into `docker-compose.yml` file when you clone this repository (see `volumes` sections under services).

Closing this issue as there is no real issue here.

Thank you
