### ISSUE TITLE
Error on `docker-compose up`

### ISSUE THREAD

**Issue by czarpino** [eko/docker-symfony#28]
# Issue

The following error displays on `docker-compose up`.

> ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
# Expected

No error
# Steps to reproduce
1. Clone repository with `$ git clone git@github.com:eko/docker-symfony.git`
2. Symlink Symfony repo to a `symfony/` dir inside `docker-symfony/`; `ln -s /path/to/project /path/to/docker-symfony/symfony`
3. Add `ip.of.docker.host    symfony.dev` to `/etc/hosts`.
4. Run `docker-compose up`
5. Error shows after the line
   
   > elk_1         | 2016-03-27 23:45:57,241 INFO success: kibana entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
   > ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
# Screenshot

![screen shot 2016-03-28 at 8 08 50 am](https://cloud.githubusercontent.com/assets/1531637/14068643/6813a5c8-f4bc-11e5-9036-0fef33245990.png)
# Notes
- I'm on OSX v10.9.5 (Mavericks)
- Running `docker-machine start default` results in:
  
  > Starting "default"...
  > Machine "default" is already running.
- The setup seems to work; I can access the symfony project at `symfony.dev` with no problem. Same with Kibana at `symfony.dev:81`.

![screen shot 2016-03-28 at 8 14 43 am](https://cloud.githubusercontent.com/assets/1531637/14068665/286318b8-f4bd-11e5-8e13-9f44417660b4.png)

![screen shot 2016-03-28 at 8 14 22 am](https://cloud.githubusercontent.com/assets/1531637/14068666/2e2ffeb4-f4bd-11e5-89f9-645d0f7c5bb4.png)

**Comment by dandries** [comment]
I have the exact same situation but on Ubuntu 14.04 .

**Comment by ErikSaunier** [comment]
I was in the same situation. My Docker virtual machine get itself into a strange state. Here is what I did in order to solve this issue:

1. Restart the environment : `docker-machine restart default`
2. Refresh your environment settings : `eval $(docker-machine env default)`

**Comment by nicklee1990** [comment]
this issue is not related to this repo. It's a Docker machine related feature where you have to connect your shell to the Docker Machine using `eval "$(docker-machine env default)"` You don't need to restart the environment. https://docs.docker.com/machine/get-started/

**Comment by eko** [comment]
Hello,

Great to see that your issue is fixed. Closing this issue now.

Thank you
