### ISSUE TITLE
user www-data not found

### ISSUE THREAD

**Issue by mmoreram** [eko/docker-symfony#34]
I get this error when docker up

2016/07/05 11:58:01 [emerg] 1#0: getpwnam("www-data") failed in /etc/nginx/nginx.conf:1

**Comment by der-kua** [comment]
+1

**Comment by Veve2** [comment]
I had the same problem, resolved by recreating the images with `docker-compose build --force-rm --no-cache --pull`

**Comment by eko** [comment]
Hello,

Great to see that your issue is fixed. Closing this issue now.

Thank you
