### ISSUE TITLE
Nginx cannot connect to upstream

### ISSUE THREAD

**Issue by fofiedelly** [eko/docker-symfony#37]
HI all, 
Thx for this project. 
I'm getting an error with nginx. Kibana is displaying without errors. 
But i'm always getting a 502 when i want to access the symfony.dev website. 
What is going wrong? 
I'm using the same conf files cloned from this repo. 
Ubutnu 14.04 Lts is my OS.

**Comment by karael** [comment]
Yep, same problem, it seem to be a connexion problem between nginx and php containers. I ll try to fix it

**Comment by wecodenlsystem** [comment]
I'm having the same problems on OS X 10.11

**Comment by joostelders** [comment]
I'm having the same problems on OS X 10.11

**Comment by fofiedelly** [comment]
@karael  can you notify us when you've fixed!

**Comment by bobman38** [comment]
same issue here on a debian8 host. I am newbie in : nginx, php-fpm and docker. Yes I don't know where to search for the issue ;)

**Comment by bobman38** [comment]
OK seems to be relative to php-fpm new config files ?

I have create a PR : https://github.com/eko/docker-symfony/pull/38

**Comment by jean-philippe-bousselin** [comment]
Same problem here on Ubuntu 14.04 and Docker 1.11.2

**Comment by eko** [comment]
Hello,

I think this issue is fixed now has the php-fpm's upstream port has been updated. Closing this issue now.

Thank you
