### ISSUE TITLE
Error: image symfony/code:latest not found

### ISSUE THREAD

**Issue by ltarasiewicz** [eko/docker-symfony#4]
I'm using the default settings. When I run `docker-compose up`, I get this error message"

> Error: image symfony/code:latest not found

**Comment by zabojad** [comment]
I had the same issue yesterday.

I've ran the three lines below and then ```docker-compose up```worked fine:
```bash
$ docker build -t symfony/code code
$ docker build -t symfony/php-fpm php-fpm
$ docker build -t symfony/nginx nginx
```

**Comment by ltarasiewicz** [comment]
A straightforward answer. That solves the problem.
