### ISSUE TITLE
always redirect to welcome to nginx not to welcome page symfony

### ISSUE THREAD

**Issue by puterakahfi** [eko/docker-symfony#40]
Hi all
I have run the docker-compose up 
but when access http://symfony.dev/, it's display welocme to nginx page not welcome page symfony
I didn't change anything, just execute docker-compose up -d 

needs help 

Thanks,
Kahfi

**Comment by eko** [comment]
Hello,

Maybe ensure that your host is the same that is used on the `nginx.conf` file.

I think this issue is fixed now so I close this issue but feel free to reopen if you still encounter any issue.

Thank you
