### ISSUE TITLE
php-fpm listens on localhost and refuses connections from nginx

### ISSUE THREAD

**Issue by dinamic** [eko/docker-symfony#41]
The php-fpm configuration is set to listen only for connections from localhost, but not from the outside world. This is why connections from nginx fail and so we receive Error 502 - Bad Gateway.

**Comment by shakealot** [comment]
Don't know if it's realy related, but I got this warning on docker-compose up :
WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.

**Comment by karael** [comment]
We shoulda do something about it

**Comment by dinamic** [comment]
I didn't had enough time to debug this, so I did my own docker-compose recipe starting from scratch.

If interested, check this repo: https://github.com/dinamic/docker-symfony

**Comment by mgallego** [comment]
I have the same issue.

The same message and the 502 error.

**Comment by mgallego** [comment]
Changing the php Dockerfile with the previous code https://github.com/eko/docker-symfony/blob/c4b4a58ad7b19590da6d2718418c7cab9877e9c6/php-fpm/Dockerfile works fine.

**Comment by fr4ngus** [comment]
If you want to install Symfony3 you have to change the following files:

<img width="420" alt="php-fpm_symfony" src="https://cloud.githubusercontent.com/assets/8094216/18852476/da652520-8440-11e6-8f03-ac4155439f06.png">
<img width="336" alt="php-fpm_dockerfile" src="https://cloud.githubusercontent.com/assets/8094216/18852477/dd32ece2-8440-11e6-96e9-70c2dd637a25.png">
<img width="637" alt="nginx_dockerfile" src="https://cloud.githubusercontent.com/assets/8094216/18852479/df50d642-8440-11e6-8a6f-30bd8ed68507.png">

**Comment by sebastianwestberg** [comment]
Thanks @fr4ngus for pointing that out. I also had to rebuild from scratch (without using cache):

docker-compose rm --all &&
 docker-compose pull &&
 docker-compose build --no-cache &&
 docker-compose up -d --force-recreate

**Comment by eko** [comment]
Hello,

Great to see that your issue is fixed. Closing this issue now.

Thank you
