### ISSUE TITLE
ctype extension missing from php image

### ISSUE THREAD

**Issue by nifr** [eko/docker-symfony#43]
After adjusting the ports in docker-compose.yml, fixing  php-fpm configuration and running the following commands:

```
docker-compose up -d
docker-compose run php /var/www/symfony/app/console
```

... I expected my Symfony 2.8 application to respond with the list of available commands but I ran into:

> ```
> PHP Fatal error:  Call to undefined function Symfony\Component\Yaml\ctype_digit() in /var/www  /symfony/vendor/symfony/symfony/src/Symfony/Component/Yaml/Inline.php on line 522
> ```

Now `docker-compose run php php -m` reveals that the `ctype` extension is NOT enabled in the `php` image.

> ```
> [PHP Modules]
> ```
> 
> apc
> apcu
> Core
> curl
> date
> ereg
> fileinfo
> filter
> gd
> hash
> iconv
> imagick
> intl
> json
> libxml
> mbstring
> mcrypt
> mysql
> mysqli
> mysqlnd
> openssl
> pcre
> PDO
> pdo_mysql
> readline
> Reflection
> session
> SimpleXML
> SPL
> standard
> tokenizer
> xml
> xmlwriter
> Zend OPcache
> zlib
> 
> [Zend Modules]
> Zend OPcache

The composition is currently **not** working with Symfony 2.8 at least.

**Comment by koga187** [comment]
I had the same problem,

edit yout file docker-symfony/php-fpm/Dockerfile 

```
FROM alpine:3.4

MAINTAINER

 Vincent Composieux <vincent.composieux@gmail.com>

RUN apk add --update \
    php5-fpm \
    php5-apcu \
    php5-curl \
    php5-gd \
    php5-cli \
    php5-ctype \
    php5-iconv \
    php5-imagick \
    php5-json \
    php5-intl \
    php5-mcrypt \
    php5-mysql \
    php5-opcache \
    php5-openssl \
    php5-pdo \
    php5-pdo_mysql \
    php5-common \
    php5-dev \
    php5-mysqli \
    php5-xml \
    php5-dom \
    php5-zlib 

RUN rm -rf /var/cache/apk/* && rm -rf /tmp/*

ADD symfony.ini /etc/php5/fpm/conf.d/
ADD symfony.ini /etc/php5/cli/conf.d/
ADD symfony.ini /etc/php5/conf.d/

ADD symfony.pool.conf /etc/php5/fpm/pool.d/

CMD ["php-fpm", "-F"]

EXPOSE 9000

```
I just add some php libs.

**Comment by BrianDGLS** [comment]
Confirmed adding `php5-ctype` to `docker-symfony/php-fpm/Dockerfile` fixes the issue for me.

**Comment by eko** [comment]
Hello,

Great to see that your issue is fixed. Closing this issue now.

Thank you
