### ISSUE TITLE
No connections until MySQL init completes

### ISSUE THREAD

**Issue by jean-pasqualini** [eko/docker-symfony#5]
If there is no database initialized when the container starts, then a default database will be created. While this is the expected behavior, this means that it will not accept incoming connections until such initialization completes. This may cause issues when using automation tools, such as docker-compose, which start several containers simultaneously.

**Comment by fesor** [comment]
How do you solve this?

**Comment by koga187** [comment]
The docker-compose file is setting the root password for mysql, then is trying to create another mysql root user, just change the ´´´MYSQL_USER´´´ if you need another user, or delete this lines to use the root in mysql.

            MYSQL_USER: root # Create new user
            MYSQL_PASSWORD: root # Create the passwd to the user above



I'm trying to use this just for mysq dev enviroment, follow my config below:

    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root #the root password
            MYSQL_DATABASE: symfony #database name

Sorry for my awful english.

**Comment by eko** [comment]
Hello,

I don't think MySQL can't accept connections until the server is ready is a real issue. Indeed, you could implement mechanisms to test if the connection is ready if you want to automate things, using entrypoints for instance.

Closing this issue for now but feel free to reopen if there is still an issue related to docker-symfony project.

Thank you
