### ISSUE TITLE
You are not allowed to access this file. Check app_dev.php for more information.

### ISSUE THREAD

**Issue by bartzaalberg** [eko/docker-symfony#50]
docker compose build goes fine, and i can access kibana, but when i try to go to symfony.dev i get a blank screen, and symfony.dev/app_dev.php; i get this "You are not allowed to access this file. Check app_dev.php for more information." Any ideas?

**Comment by leroy0211** [comment]
app_dev is secured so localhost access only. Because you are running inside a docker, your own machine is not the localhost. 
You have to allow your ip-address in the `web/app_dev.php` file in your symfony folder, or just remove the complete security in that file.

**Comment by bartzaalberg** [comment]
Then i get the following error which also doesnt seem so normal.
RuntimeException in ClassCollectionLoader.php line 272: Failed to write cache file "/var/www/symfony/var/cache/dev/classes.php".

**Comment by B-Galati** [comment]
Just chmod 777 on your `app/cache` and `app/log` directory.
Better solutions are proposed on the doc here -> http://symfony.com/doc/current/setup/file_permissions.html

**Comment by bartzaalberg** [comment]
Thanks, this and installing hp5-ctype and php5-dom extensions did the job

**Comment by eko** [comment]
Hello,

Thank you everyone for your help in this issue.

Closing this issue as it appears to be fixed now.
