### ISSUE TITLE
Fedora: Unable to create the cache directory

### ISSUE THREAD

**Issue by house-md** [eko/docker-symfony#51]
Hi I have problem with setting permissions for my second computer with Fedora 25.
when I run symfony project over lamp everything is working but when I start it using docker I have this error message "Unable to create the cache directory".
My main computer is running osx and everyting is okay, but with Fedora I have problem with permissions for my symfony apps with docker.

I tried change permissions to 777 also commands from symfony doc (http://symfony.com/doc/current/setup/file_permissions.html)

Thank you.
MD

**Comment by viperdigo** [comment]
i have same problem, but my docker installed in my OSX, i try 777 in directories, but not work too.

**Comment by ducreuxr** [comment]
Same problem on Ubuntu 16.04.

**Comment by ducreuxr** [comment]
I fixed this by changing permissions of `var/cache/` and `var/logs/.

**Comment by eko** [comment]
Hello,

Thank you for your answer and happy to see that you've fixed your issue :) Closing this issue now.
