### ISSUE TITLE
Slow synchronization

### ISSUE THREAD

**Issue by matheusgontijo** [eko/docker-symfony#52]
Hey guys, I'm facing a very hard time on files synchronization. It takes every request about 20-30 seconds to update my files to docker.

Any clue?

**Comment by flemzord** [comment]
@matheusgontijo macOS ?

**Comment by matheusgontijo** [comment]
Fedora 25 (64 bits)

2017-04-21 5:18 GMT-03:00 Maxence Maireaux <notifications@github.com>:

**Comment by eko** [comment]
Hello,

I am sorry about Docker performances of Fedora. Maybe latest versions has gain performances?

Elsewhere, you could try this tool that appears to work properly: http://docker-sync.io/

I close this issue as it is not related to this project.

Thank you
