### ISSUE TITLE
File not found when trying to access Symfony project

### ISSUE THREAD

**Issue by jokoast** [eko/docker-symfony#63]
Hi,

I followed the instructions about how to install it but when i try to access my symfony project.
If i try to access Kibana, it works.

```
> docker-compose ps 
        Name                       Command               State              Ports           
--------------------------------------------------------------------------------------------
dockersymfony_db_1      docker-entrypoint.sh mysqld      Up      0.0.0.0:3306->3306/tcp     
dockersymfony_elk_1     /usr/bin/supervisord -n -c ...   Up      0.0.0.0:81->80/tcp         
dockersymfony_nginx_1   nginx                            Up      443/tcp, 0.0.0.0:80->80/tcp
dockersymfony_php_1     php-fpm7 -F                      Up      0.0.0.0:9000->9000/tcp 
```

I have 127.0.0.1 and 0.0.0.0 in my hosts 

I created a new symfony project at the root of the folder like that

```
> symfony new symfony
> ls 
LICENSE.md                 docker-compose.travis.yml  elk/                       nginx/                     symfony/
README.md                  docker-compose.yml         logs/                      php-fpm/
```

How can i success ?

Thank's in advance

**Comment by MHaendel** [comment]
Same problem.

**Comment by tomasyhy** [comment]
I also come across this issue.

**Comment by uprix** [comment]
Hi,
I got it working.

There are two issues:
1) The master branch relies on the filesystem-layout of Symfony 4. If your symfony-directory does not match to  ```nginx/symfony.conf``` then nginx doesn't get access.
Solution:
- the 'root'-entry must either be '/var/www/symfony/public' (Sf 4) or '/var/www/symfony/web' (Sf3). Next the - redirect must be 'index.php' or 'app.php'

2) After fixing that I ran into troubles with php-fpm. There is at least (depending on your app - I my case it was just a 'symfony new symfony') a missing 'php7-session' module. So add it too 'php-fpm/Dockerfile'
Next you get the famous permission problems of the webserver to your var/cache, var/session an here to logs/symfony folders. I solves these to get the 'swarm' running via 'chmod -R 777 ...'

**Comment by cve** [comment]
I have Symfony 4, and no advice helps from above, I'm still have 404 nginx not found...

**Comment by mvaljento** [comment]
@cve Did you ever solve this?

**Comment by cve** [comment]
@mvaljento I'm used https://phpdocker.io/generator

**Comment by mvaljento** [comment]
@cve, Cheers mate. Didn't know that one. Thanks!

**Comment by r3m4k3** [comment]
What about changing symfony.conf to something like that:

```
server {
    server_name myapp.local;
    root /var/www/symfony/public;

    location / {
        try_files $uri @rewriteapp;
    }

    location @rewriteapp {
        rewrite ^(.*)$ /index.php/$1 last;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php-upstream;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param HTTPS off;
        # Prevents URIs that include the front controller. This will 404:
        # http://domain.tld/index.php/some-path
        # Remove the internal directive to allow URIs like this
        internal;
    }

    # return 404 for all other php files not matching the front controller
    # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/symfony_error.log;
    access_log /var/log/nginx/symfony_access.log;
}
```

**Comment by eko** [comment]
Thank you for all your answers.

Closing this ticket as it appears this is a particular issue concerning symlinks.

**Comment by newQuery** [comment]
> Hi,
> I got it working.
> 
> IMHO there are three issues:
> 
> 1. The master branch relies on the filesystem-layout of Symfony 4. If your symfony-directory does not match to  `nginx/symfony.conf` then nginx doesn't get access.
> 
> Solution:
> 
> * the 'root'-entry must be either '/var/www/symfony/public' (Sf 4) or '/var/www/symfony/web' (Sf3)
> * the - redirect must be 'index.php' or 'app.php'
> * Alternatively you could switch to the sf-3 branch I think.
> 
> 1. After fixing that I ran into troubles with php-fpm. There is at least (depending on your app - in my case it was just created by `symfony new symfony`) a missing 'php7-session' module. So add it too 'php-fpm/Dockerfile'.
> 2. Next you get the famous symfony permission problems of the webserver to your 'var/cache', 'var/session' and in this context also to 'logs/symfony' folders (https://symfony.com/doc/3.4/setup/file_permissions.html). I solved this to get the 'swarm' running just via 'chmod -R 777 ...'
> 
> Then I received "Welcome to Symfony 3.3.10 ..."

Never chmod 777 please, for christ sake

**Comment by farazpartoei** [comment]
This worked for me
 run `composer require symfony/apache-pack` inside container wwwroot path
