### ISSUE TITLE
.dev domains redirected to https in latest versions of Chrome

### ISSUE THREAD

**Issue by sverraest** [eko/docker-symfony#67]
More info here: https://tech.slashdot.org/story/17/09/18/192227/chrome-to-force-domains-ending-with-dev-and-foo-to-https-via-preloaded-hsts

Consider switching to another top level domain

**Comment by supertanuki** [comment]
`.vm` ?

**Comment by zbrag** [comment]
.vm wouldn't be wise, the best options are the ones which are already listed as 'never to be used' by [icann](https://en.wikipedia.org/wiki/.localhost), so that would mean: .example, .test, .localhost.

I would suggest .test ?

**Comment by supertanuki** [comment]
@zbrag There is an issue with .localhost tld, [see here](https://bugs.chromium.org/p/chromium/issues/detail?id=489973)
.test can be misleading, as we can have a test environment.
.example?

**Comment by Padrio** [comment]
This can be closed since #74 fixed this.

**Comment by eko** [comment]
Thanks for reporting this issue, this has been fixed by @Padrio :)
