### ISSUE TITLE
PHP compatibility and Symfony 4 bundles 

### ISSUE THREAD

**Issue by kamalkech** [eko/docker-symfony#68]
I guess this image need to update php from 7.0.x to 7.1.x, because they are somes bundles require php 7.1.x

https://monosnap.com/file/qLsZ21Z7ZUQggCJd2Ypxf0Zt4X9RN0

**Comment by eko** [comment]
Hello @kamalkech,

php-fpm Dockerfile uses alpine:3.6 which uses php-fpm 7.1.9, see: https://pkgs.alpinelinux.org/packages?name=php7-fpm&branch=v3.6

I think you are trying to install dependencies from your host machine?

I am closing this issue, please feel free to reopen if you think it is still not relevent.

THank you
