### ISSUE TITLE
Call to undefined function simplexml_import_dom()

### ISSUE THREAD

**Issue by bdaler** [eko/docker-symfony#76]
issue: missing php7-simplexml in php-fpm container
slove:
inside container, apk add --no-cache php7-simplexml
or add php7-simplexml to Dockerfile on php-fpm folder

**Comment by eko** [comment]
Hello,

Maybe you're not up-to-date with latest version of this repository. Indeed, `php7-simplexml` package has been added, as you can see here: https://github.com/eko/docker-symfony/blob/master/php-fpm/Dockerfile#L28

I am closing this issue as it is not still relevent.

Thank you
