### ISSUE TITLE
Session Storage was not able to create directory "/var/www/symfony/var/sessions/dev"

### ISSUE THREAD

**Issue by jcfrane** [eko/docker-symfony#77]
Hi, 

I have installed Symfony 4. 

Now, when I tried to access the page it says that:

**Session Storage was not able to create directory "/var/www/symfony/var/sessions/dev"**

I know this is file permissions, i tried to chmod and chown the var folder but still no luck.

**Comment by funkimunky** [comment]
I had to set the folder permissions to 777 as php-fpm runs a user nobody group nobody this mean that chmod doesnt help. I had to do this for the log file locations as well.
Im not really that good on setting the correct permissions so I dont know if this is right.

**Comment by eko** [comment]
Hello, this is just about setting the right permissions on your Symfony cache/logs folder.

I hope you have succeed in this now.

I close this issue but feel free to re-open if it is still relevent.

Thank you
