### ISSUE TITLE
php & composer commands not found inside dockersymfony_nginx_1

### ISSUE THREAD

**Issue by thamerbelfkihthamer** [eko/docker-symfony#82]
First of all, I want to think all the contributors to this amazing work.

I have installed this depo, and when I was inside the nginx container with ` docker exec -it dockersymfony_nginx_1 sh` i can't execute both php and composer commands inside the container.

Ps: inside the /etc folder i don't found the php folder

how I can resolve this issue, please

**Comment by Padrio** [comment]
You have to execute it inside the php-fpm Container.

**Comment by thamerbelfkihthamer** [comment]
hum, thanks man, we installed them with Dockerfile of php-fpm image
