### ISSUE TITLE
Support for Symfony4 and MongoDB

### ISSUE THREAD

**Issue by roydondsouza** [eko/docker-symfony#84]
Hi, Possible to tweak things and let us know how can we support mongodb here?

**Comment by eko** [comment]
Hello @roydondsouza,

To install MongoDB, you have to add a MongoDB container into the `docker-compose.yml` file stack, you can find some examples here on the official mongo Docker image: https://store.docker.com/images/mongo

Also, you will need to install PHP's mongodb extension (`php7-mongodb`: https://pkgs.alpinelinux.org/package/v3.8/community/x86/php7-mongodb).

I close this issue.

Thank you

**Comment by roydondsouza** [comment]
Thank you for taking the time to respond @eko
