### ISSUE TITLE
Pb docker-compose

### ISSUE THREAD

**Issue by tilk-theapp** [eko/docker-symfony#9]
I'm facing this docker-compose problem even if I'm using the config file as is on git.
I'm running on Boot2Docker-cli version: v1.7.0 on Mac OS.

```
➜  docker-symfony git:(master) docker-compose up  
Pulling application (symfony/code:latest)...
Pulling repository symfony/code
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
```

Do you have any ideas?

**Comment by tomaszhanc** [comment]
I think you need first build all images:
    $ docker build -t symfony/code code
    $ docker build -t symfony/php-fpm php-fpm
    $ docker build -t symfony/nginx nginx

**Comment by gtrias** [comment]
thx @tomaszhanc for the tip.

@eko shouldn't come this in README or this should be handled by docker-compose?

**Comment by mickaelandrieu** [comment]
@gtrias it is in the README :)

**Comment by eko** [comment]
I think it should be pull up in the README section, you're right, as this is actually marked as optional, which is wrong :)

You can submit a PR to fix that or I will fix it as soon as possible.

Thank you!

**Comment by gtrias** [comment]
nice fix, Thank you!
