### ISSUE TITLE
problem to create data base

### ISSUE THREAD

**Issue by kaneabdou** [eko/docker-symfony#91]
In AbstractMySQLDriver.php line 113:
                                                                              
  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused  
                                                                              

In PDOConnection.php line 50:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 46:
                                             
  SQLSTATE[HY000] [2002] Connection refused

**Comment by victorfrl** [comment]
Hi, check if  database service is up or user and password of your database service are corrects.

**Comment by wabbenhuis** [comment]
Also validate that you are using `db` as the database host (and not `127.0.0.1` or `localhost`)
Like so: `mysql://symfony:symfony@db:3306/symfony`

**Comment by eko** [comment]
Thank you for your answers on this issue guys.

Indeed, you should use `db` (the docker-compose service name) as the hostname in your Symfony application configuration.

Closing this issue as I think it's not a real issue.
