### ISSUE TITLE
listen port

### ISSUE THREAD

**Issue by nicraMarcin** [eko/docker-symfony#98]
https://github.com/eko/docker-symfony/blob/c706154571ab921262d47096e812ccb4f34f7695/php-fpm/symfony.pool.conf#L20

Acording to this symfony pool listens on 9001 port but Dockerfie exposes 9000 (default www.pool).
Shouldn't be changed

**Comment by eko** [comment]
Hi @nicraMarcin,

You're right, could you please open a PR to fix that?

Thank you

**Comment by nicraMarcin** [comment]
Ok

**Comment by nicraMarcin** [comment]
PR has been pull
